blueprint:
  name: Garbage reminder (daysTo)
  domain: automation
  input:
    reminder_time:
      name: Reminder time
      description: Uhrzeit der Erinnerung am Vortag / mit Offset
      default: '18:00:00'
      selector:
        time: {}
    day_offset:
      name: Day offset
      description: Wieviele Tage im Voraus erinnert werden soll (1 = morgen, 0 = heute usw.)
      default: 1
    reminder_title:
      name: Reminder title
      default: Garbage reminder
    reminder_message:
      name: Reminder message
      default: 'Morgen wird abgeholt: '
    notifier:
      name: Notifier
      description: z.B. notify.notify
      default: notify.notify

    garbage_sensor_1:
      name: Garbage sensor 1
      selector:
        entity:
          filter:
            - domain:
                - sensor
          multiple: false
      default: ''
    garbage_sensor_2:
      name: Garbage sensor 2
      selector:
        entity:
          filter:
            - domain:
                - sensor
          multiple: false
      default: ''
    garbage_sensor_3:
      name: Garbage sensor 3
      selector:
        entity:
          filter:
            - domain:
                - sensor
          multiple: false
      default: ''
    garbage_sensor_4:
      name: Garbage sensor 4
      selector:
        entity:
          filter:
            - domain:
                - sensor
          multiple: false
      default: ''

    # Name des Attributs mit der Restzeit – bei dir "daysTo"
    garbage_sensor_days_attr:
      name: Days-to attribute
      description: Attribut am Sensor, das die Resttage enthält
      default: daysTo

  source_url: https://github.com/reniko/ha-blueprints/blob/main/garbage-reminder.yaml

variables:
  garbage_sensor_1: !input garbage_sensor_1
  garbage_sensor_2: !input garbage_sensor_2
  garbage_sensor_3: !input garbage_sensor_3
  garbage_sensor_4: !input garbage_sensor_4
  reminder_title: !input reminder_title
  reminder_message: !input reminder_message
  day_offset: !input day_offset
  garbage_sensor_days_attr: !input garbage_sensor_days_attr

  # Baue eine Liste (Friendly Name, daysTo) und filtere auf gewünschten Offset
  sensors_due: >-
    {{
      [
        (state_attr(garbage_sensor_1, 'friendly_name'), state_attr(garbage_sensor_1, garbage_sensor_days_attr)),
        (state_attr(garbage_sensor_2, 'friendly_name'), state_attr(garbage_sensor_2, garbage_sensor_days_attr)),
        (state_attr(garbage_sensor_3, 'friendly_name'), state_attr(garbage_sensor_3, garbage_sensor_days_attr)),
        (state_attr(garbage_sensor_4, 'friendly_name'), state_attr(garbage_sensor_4, garbage_sensor_days_attr))
      ]
      | selectattr('1', 'equalto', day_offset | int)
      | map(attribute=0)
      | join(', ')
    }}

trigger:
  - platform: time
    at: !input reminder_time

condition:
  - condition: template
    value_template: "{{ sensors_due != '' }}"

action:
  - service: !input notifier
    data:
      title: "{{ reminder_title }}"
      message: "{{ reminder_message }}{{ sensors_due }}"
