alias: Bewässerung (PV & Regen)
description: Triggert das Bewässerungs-Skript
triggers:
  - entity_id:
      - sensor.pv_uberschuss_geglattet
    above: input_number.irrigation_pump_power
    trigger: numeric_state
    for:
      hours: 0
      minutes: 5
      seconds: 0
  - entity_id: sensor.solis_battery_soc
    above: input_number.irrigation_min_soc
    trigger: numeric_state
  - trigger: time
    at: input_datetime.irrigation_late
conditions:
  - condition: state
    entity_id: script.irrigation_sequence
    state: 'off'
  - condition: or
    conditions:
      - condition: and
        conditions:
          - condition: or
            conditions:
              - condition: numeric_state
                entity_id: input_number.lawn_front_runtime
                above: 0
              - condition: numeric_state
                entity_id: input_number.lawn_back_runtime
                above: 0
          - condition: time
            after: input_datetime.irrigation_early
            before: input_datetime.irrigation_late
          - condition: or
            conditions:
              - condition: and
                conditions:
                  - condition: state
                    entity_id: binary_sensor.lawn_preemtive_watering
                    state: 'on'
                  - condition: state
                    entity_id: binary_sensor.irrigation_rain_expected
                    state: 'off'
                  - condition: numeric_state
                    entity_id: sensor.solis_battery_soc
                    above: input_number.irrigation_min_soc
                  - condition: numeric_state
                    entity_id: sensor.pv_uberschuss_geglattet
                    above: input_number.irrigation_pump_power
                  - condition: numeric_state
                    entity_id: sensor.irrigation_total_power_needed
                    below: sensor.today_remaining_pv_surplus
                    enabled: false
                  - condition: template
                    value_template: >-
                      {{ states('sensor.irrigation_total_power_needed') |
                      float(0) < states('sensor.today_remaining_pv_surplus') |
                      float(0) }}
              - condition: state
                entity_id: binary_sensor.lawn_too_long_dry
                state: 'on'
      - condition: and
        conditions:
          - condition: numeric_state
            entity_id: input_number.hedge_runtime
            above: 0
          - condition: state
            entity_id: binary_sensor.irrigation_rain_expected
            state: 'off'
          - condition: numeric_state
            entity_id: sensor.solis_battery_soc
            above: input_number.irrigation_min_soc
          - condition: numeric_state
            entity_id: sensor.pv_uberschuss_geglattet
            above: input_number.irrigation_pump_power
          - condition: numeric_state
            entity_id: sensor.irrigation_total_power_needed
            below: sensor.today_remaining_pv_surplus
            enabled: false
          - condition: template
            value_template: >-
              {{ states('sensor.irrigation_total_power_needed') | float(0) <
              states('sensor.today_remaining_pv_surplus') | float(0) }}
actions:
  - action: script.turn_on
    metadata: {}
    target:
      entity_id: script.irrigation_sequence
    data: {}
mode: single
trace:
  stored_traces: 50
